### ISSUE TITLE
Which is the pretrain model in train.sh?

### ISSUE THREAD

**Issue by pydxflwb** [charliememory/Disentangled-Person-Image-Generation#11]
Hello, I'm a little bit confused that which the pretained model directory is in the train script. Should I use the pretrained model you provided? Or just use the training model itself?

**Comment by charliememory** [comment]
Yes, in the train script, the pretained model directory could be the training model itself, as you want to train the stage-II sampling models for your own stage-I reconstruction models. In brief, you can set ${log_dir} and ${log_dir_pretrain}  to the same directory.

**Comment by pydxflwb** [comment]
Thanks a lot!
