### ISSUE TITLE
403 error when trying to download the datasets...

### ISSUE THREAD

**Issue by VieVie31** [charliememory/Disentangled-Person-Image-Generation#5]
Hi, this project seems great, so I wanted to reproduce it in PyTorch, but unfortunately I couldn't download the datasets... :'(

![capture d ecran 2018-07-05 a 13 59 34](https://user-images.githubusercontent.com/14021207/42322149-a5bd3ace-805b-11e8-8816-44f5ca7bef3e.png)

**Comment by charliememory** [comment]
Sorry for the problem. There is some IT issue with our server. We will fix it asap.

**Comment by charliememory** [comment]
The problem has been fixed now.
