### ISSUE TITLE
How to convert a 352-dim vector to 128*64*(352 channels) by "tile"?

### ISSUE THREAD

**Issue by budui** [charliememory/Disentangled-Person-Image-Generation#9]
Hi,thanks for your great paper first!

Because the code has not been released yet, I'm confused about this fragment from paper:
> the foreground and background features are concatenated and tiled into 128×64×352 appearance feature maps.

Can you tell me how this is achieved? Just copy-paste each value of the 352-dim vector 128*64 times?

**Comment by charliememory** [comment]
Yes, just repeat 128×64×1 into 128×64×352.
